# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14fff46afc586353f13a50e4ec11320de2cc54c2cb547c8caf7d886941ec7c6c352c656564021158feadf47228c5963eddc183c230790de101e0df81e153781c

test:
  secret_key_base: 5af14bd2d56db3af21e11c25b1554b1b9b61e0fde99882b173923648e385896cc342fc491527af33917dd68218497d7e2cf6b0e47336c91127a4729d3300dc05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
